server:
  port: 9090
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://106.15.248.131:3306/online_exam_system?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: leixuesong
mybatis:
  mapper-locations: classpath*:com/xihua/dao/mapper/*.xml
  type-aliases-package: com.xihua.entity
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
pagehelper:
  helper-dialect: mysql
